import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <header className="w-full bg-white/80 backdrop-blur shadow-sm mb-6 sticky top-0 z-50 border-b border-gray-100">
          <nav className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between px-2 sm:px-4 py-3 gap-2 sm:gap-0">
            <Link
              href="/"
              className="text-xl sm:text-2xl font-extrabold text-indigo-700 tracking-tight drop-shadow"
            >
              DesignFlow Pro
            </Link>
            <div className="flex flex-wrap gap-2 sm:gap-4 text-base font-medium justify-center">
              <Link
                href="/dashboard"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                仪表盘
              </Link>
              <Link
                href="/projects"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                项目管理
              </Link>
              <Link
                href="/clients"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                客户管理
              </Link>
              <Link
                href="/tools/proposal-generator"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                AI提案
              </Link>
              <Link
                href="/tools/invoice-generator"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                发票
              </Link>
              <Link
                href="/tools/feedback-collector"
                className="text-gray-700 hover:text-indigo-600 transition"
              >
                反馈
              </Link>
            </div>
          </nav>
        </header>
        <main className="min-h-[80vh] flex flex-col items-center justify-center px-2 sm:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
